services:
  vikunja:
    image: docker.1ms.run/vikunja/vikunja:2.1.0
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    environment:
      - VIKUNJA_DATABASE_HOST=${PANEL_DB_HOST}
      - VIKUNJA_DATABASE_PORT=${PANEL_DB_PORT}
      - VIKUNJA_DATABASE_PASSWORD=${PANEL_DB_USER_PASSWORD}
      - VIKUNJA_DATABASE_USER=${PANEL_DB_USER}
      - VIKUNJA_DATABASE_DATABASE=${PANEL_DB_NAME}
      - VIKUNJA_DATABASE_TYPE=${PANEL_DB_TYPE}
      - VIKUNJA_SERVICE_JWTSECRET=${SECRET_KEY}
      - VIKUNJA_SERVICE_PUBLICURL=${PANEL_APP_URL}
    volumes:
      - ./data/files:/app/vikunja/files
    ports:
      - ${PANEL_APP_PORT_HTTP}:3456
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
