services:
  rmqtt:
    image: rmqtt/rmqtt:0.18.1
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_MQTT}:1883
      - ${PANEL_APP_PORT_MQTTS}:8883
      - ${PANEL_APP_PORT_HTTP}:6060
      - ${PANEL_APP_PORT_WS}:8083
    volumes:
      - ./data/log:/var/log/rmqtt
      - ./data/jwt:/app/rmqtt/data/jwt
      - ./init_jwt.sh:/docker-entrypoint.d/init_jwt.sh:ro
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - RMQTT_CONFIG=${RMQTT_CONFIG}
      - RMQTT_ACL_CONFIG=${RMQTT_ACL_CONFIG}
      - RMQTT_JWT_CONFIG=${RMQTT_JWT_CONFIG}
      - JWT_PUBLIC_KEY_PEM=${JWT_PUBLIC_KEY_PEM}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
