services:
  rmqtt:
    image: rmqtt/rmqtt:0.18.1
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_MQTT}:1883
      - ${PANEL_APP_PORT_MQTTS}:8883
      - ${PANEL_APP_PORT_HTTP}:6060
      - ${PANEL_APP_PORT_WS}:8083
    volumes:
      - ./data/log:/var/log/rmqtt
      - ./data/config:/etc/rmqtt
      - ./data/plugins:/app/rmqtt/rmqtt-plugins
      - ./data/jwt:/app/rmqtt/data/jwt
      - ./init_jwt.sh:/docker-entrypoint.d/init_jwt.sh:ro
    environment:
      - TZ=${TIMEZONE:-Asia/Shanghai}
      - JWT_AUTH_ENABLED=${JWT_AUTH_ENABLED:-false}
      - JWT_PUBLIC_KEY_PEM=${JWT_PUBLIC_KEY_PEM}
      - JWT_FROM=${JWT_FROM:-password}
      - JWT_DISCONNECT_IF_EXPIRY=${JWT_DISCONNECT_IF_EXPIRY:-true}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_CLAIMS_CONFIG=${JWT_CLAIMS_CONFIG}
    command: >
      --id 1
      --listen-addrs "0.0.0.0:1883"
      --listen-addrs "0.0.0.0:8883"
      --ws-listen-addrs "0.0.0.0:8083"
      --http-listen-addr "0.0.0.0:6060"
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
