services:
  spug:
    image: openspug/spug:3.3.2
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    environment:
      - DATABASE_HOST=${PANEL_DB_HOST}
      - DATABASE_PORT=${PANEL_DB_PORT}
      - DATABASE_NAME=${PANEL_DB_NAME}
      - DATABASE_USER=${PANEL_DB_USER}
      - DATABASE_PASSWORD=${PANEL_DB_USER_PASSWORD}
      - DATABASE_TYPE=${PANEL_DB_TYPE}
      - SECRET_KEY=${SECRET_KEY}
      - SPUG_ADMIN_USER=${SPUG_ADMIN_USER}
      - SPUG_ADMIN_PASSWORD=${SPUG_ADMIN_PASSWORD}
    ports:
      - "0.0.0.0:${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - ./data/spug:/data
      - ./init_spug.sh:/docker-entrypoint.d/init_spug.sh:ro
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
